# Generated by Django 4.0.4 on 2022-05-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=80)),
                ('department_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RealEstateAgency.department')),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RealEstateAgency.employee')),
                ('district', models.CharField(max_length=200)),
            ],
            bases=('RealEstateAgency.employee',),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_dep',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RealEstateAgency.employee'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], max_length=1)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RealEstateAgency.client')),
                ('realtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RealEstateAgency.realtor')),
            ],
            options={
                'unique_together': {('realtor', 'client')},
            },
        ),
    ]
